### PR TITLE
Upgrade grpc and remove unused method

### PR DESCRIPTION
**Pull request by Sineaggi**
The method was removed upstream https://github.com/grpc/grpc-java/pull/10744

### CODE REVIEW

**Comment by Sineaggi** [comment]
Relates to https://github.com/grpc-ecosystem/grpc-spring/pull/1030

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
Please resolve the conflicts.

**Comment by Sineaggi** [comment]
> Please resolve the conflicts.

Rebased

**Comment by ST-DDT** [comment]
Please remove it also from here: https://github.com/grpc-ecosystem/grpc-spring/blob/d75fba5346846bac86e8f782e12d3bdadf322360/grpc-client-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L57

**Comment by Sineaggi** [comment]
@ST-DDT It is done

**Review by ST-DDT — APPROVED** [review]

**Comment by Sineaggi** [comment]
Good to merge?

**Review by yidongnan — APPROVED** [review]
LGTM

**Pull request merged**
